# SPDX-FileCopyrightText: 1998 Argonne National Laboratory
# SPDX-FileCopyrightText: Michael Davidsaver and the reccaster contributors
#
# SPDX-License-Identifier: EPICS

TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DB += reccaster.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
